//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.Ui.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Desktop.Ui.I18n.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ES Power Tool.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikaci.
        /// </summary>
        public static string label_about {
            get {
                return ResourceManager.GetString("label_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        public static string label_built_in {
            get {
                return ResourceManager.GetString("label_built_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string label_common_category {
            get {
                return ResourceManager.GetString("label_common_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Paths.
        /// </summary>
        public static string label_csv_category {
            get {
                return ResourceManager.GetString("label_csv_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to CSV default Preset.
        /// </summary>
        public static string label_default_preset_csv_path {
            get {
                return ResourceManager.GetString("label_default_preset_csv_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivable.
        /// </summary>
        public static string label_derivable {
            get {
                return ResourceManager.GetString("label_derivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string label_description {
            get {
                return ResourceManager.GetString("label_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Type.
        /// </summary>
        public static string label_element_type {
            get {
                return ResourceManager.GetString("label_element_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string label_folder {
            get {
                return ResourceManager.GetString("label_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to CSV Folder.
        /// </summary>
        public static string label_folder_csv_path {
            get {
                return ResourceManager.GetString("label_folder_csv_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string label_generate {
            get {
                return ResourceManager.GetString("label_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string label_loading {
            get {
                return ResourceManager.GetString("label_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string label_name {
            get {
                return ResourceManager.GetString("label_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string label_new_project {
            get {
                return ResourceManager.GetString("label_new_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        public static string label_open_project {
            get {
                return ResourceManager.GetString("label_open_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string label_optional {
            get {
                return ResourceManager.GetString("label_optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string label_preset {
            get {
                return ResourceManager.GetString("label_preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to CSV Presets.
        /// </summary>
        public static string label_preset_csv_path {
            get {
                return ResourceManager.GetString("label_preset_csv_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to CSV Preset Element.
        /// </summary>
        public static string label_preset_element_csv_path {
            get {
                return ResourceManager.GetString("label_preset_element_csv_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string label_project {
            get {
                return ResourceManager.GetString("label_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime ID.
        /// </summary>
        public static string label_runtime_id {
            get {
                return ResourceManager.GetString("label_runtime_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific.
        /// </summary>
        public static string label_specific_category {
            get {
                return ResourceManager.GetString("label_specific_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super types.
        /// </summary>
        public static string label_supertypes {
            get {
                return ResourceManager.GetString("label_supertypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string label_type {
            get {
                return ResourceManager.GetString("label_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to CSV Type.
        /// </summary>
        public static string label_type_csv_path {
            get {
                return ResourceManager.GetString("label_type_csv_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type element.
        /// </summary>
        public static string label_type_element {
            get {
                return ResourceManager.GetString("label_type_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to CSV Type Element.
        /// </summary>
        public static string label_type_element_csv_path {
            get {
                return ResourceManager.GetString("label_type_element_csv_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to super type.
        /// </summary>
        public static string label_type_type_csv_path {
            get {
                return ResourceManager.GetString("label_type_type_csv_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique name.
        /// </summary>
        public static string label_unique_name {
            get {
                return ResourceManager.GetString("label_unique_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove &apos;{0}&apos;?.
        /// </summary>
        public static string question_do_you_want_to_remove_object_message {
            get {
                return ResourceManager.GetString("question_do_you_want_to_remove_object_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the selected objects?.
        /// </summary>
        public static string question_do_you_want_to_remove_objects_message {
            get {
                return ResourceManager.GetString("question_do_you_want_to_remove_objects_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset &apos;{0}&apos; is used as associated preset for composite preset element &apos;{1}&apos;.
        /// </summary>
        public static string validation_message_preset_is_associated_to_preset_element {
            get {
                return ResourceManager.GetString("validation_message_preset_is_associated_to_preset_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is used as a supertype for &apos;{1}&apos;.
        /// </summary>
        public static string validation_message_type_is_used_as_super_type {
            get {
                return ResourceManager.GetString("validation_message_type_is_used_as_super_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is used as a element type for composite type element &apos;{1}&apos;.
        /// </summary>
        public static string validation_message_type_is_used_as_type_element {
            get {
                return ResourceManager.GetString("validation_message_type_is_used_as_type_element", resourceCulture);
            }
        }
    }
}
