//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desktop.Ui.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Desktop.Ui.I18n.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ES Power Tool.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during generating the CSV files.
        /// </summary>
        public static string error_message_generated_csv_failed {
            get {
                return ResourceManager.GetString("error_message_generated_csv_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string label_about {
            get {
                return ResourceManager.GetString("label_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        public static string label_built_in {
            get {
                return ResourceManager.GetString("label_built_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string label_cancel {
            get {
                return ResourceManager.GetString("label_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string label_close {
            get {
                return ResourceManager.GetString("label_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close project.
        /// </summary>
        public static string label_close_project {
            get {
                return ResourceManager.GetString("label_close_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string label_code {
            get {
                return ResourceManager.GetString("label_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name.
        /// </summary>
        public static string label_column_name {
            get {
                return ResourceManager.GetString("label_column_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Column.
        /// </summary>
        public static string label_column_name_annotation {
            get {
                return ResourceManager.GetString("label_column_name_annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string label_common_category {
            get {
                return ResourceManager.GetString("label_common_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composite preset element.
        /// </summary>
        public static string label_composite_preset_element {
            get {
                return ResourceManager.GetString("label_composite_preset_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string label_count {
            get {
                return ResourceManager.GetString("label_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV Paths.
        /// </summary>
        public static string label_csv_category {
            get {
                return ResourceManager.GetString("label_csv_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default data type conversions.
        /// </summary>
        public static string label_default_conversions_of_data_types {
            get {
                return ResourceManager.GetString("label_default_conversions_of_data_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to CSV default Preset.
        /// </summary>
        public static string label_default_preset_csv_path {
            get {
                return ResourceManager.GetString("label_default_preset_csv_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivable.
        /// </summary>
        public static string label_derivable {
            get {
                return ResourceManager.GetString("label_derivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string label_description {
            get {
                return ResourceManager.GetString("label_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element Type.
        /// </summary>
        public static string label_element_type {
            get {
                return ResourceManager.GetString("label_element_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string label_exit {
            get {
                return ResourceManager.GetString("label_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string label_finish {
            get {
                return ResourceManager.GetString("label_finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string label_folder {
            get {
                return ResourceManager.GetString("label_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to CSV Folder.
        /// </summary>
        public static string label_folder_csv_path {
            get {
                return ResourceManager.GetString("label_folder_csv_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string label_generate {
            get {
                return ResourceManager.GetString("label_generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate CSV.
        /// </summary>
        public static string label_generate_csv {
            get {
                return ResourceManager.GetString("label_generate_csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate UUID.
        /// </summary>
        public static string label_generate_guid {
            get {
                return ResourceManager.GetString("label_generate_guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Liquibase.
        /// </summary>
        public static string label_generate_liquibase {
            get {
                return ResourceManager.GetString("label_generate_liquibase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated code.
        /// </summary>
        public static string label_generated_code {
            get {
                return ResourceManager.GetString("label_generated_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Id.
        /// </summary>
        public static string label_id_annotation {
            get {
                return ResourceManager.GetString("label_id_annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java code data type.
        /// </summary>
        public static string label_java_data_type {
            get {
                return ResourceManager.GetString("label_java_data_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquibase.
        /// </summary>
        public static string label_liquibase_category {
            get {
                return ResourceManager.GetString("label_liquibase_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string label_loading {
            get {
                return ResourceManager.GetString("label_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string label_message {
            get {
                return ResourceManager.GetString("label_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string label_messages {
            get {
                return ResourceManager.GetString("label_messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string label_name {
            get {
                return ResourceManager.GetString("label_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string label_new_project {
            get {
                return ResourceManager.GetString("label_new_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string label_ok {
            get {
                return ResourceManager.GetString("label_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project.
        /// </summary>
        public static string label_open_project {
            get {
                return ResourceManager.GetString("label_open_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string label_optional {
            get {
                return ResourceManager.GetString("label_optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string label_preset {
            get {
                return ResourceManager.GetString("label_preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to CSV Presets.
        /// </summary>
        public static string label_preset_csv_path {
            get {
                return ResourceManager.GetString("label_preset_csv_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to CSV Preset Element.
        /// </summary>
        public static string label_preset_element_csv_path {
            get {
                return ResourceManager.GetString("label_preset_element_csv_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string label_project {
            get {
                return ResourceManager.GetString("label_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string label_reference {
            get {
                return ResourceManager.GetString("label_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove brackets.
        /// </summary>
        public static string label_remove_brackets {
            get {
                return ResourceManager.GetString("label_remove_brackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime ID.
        /// </summary>
        public static string label_runtime_id {
            get {
                return ResourceManager.GetString("label_runtime_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string label_settings {
            get {
                return ResourceManager.GetString("label_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific.
        /// </summary>
        public static string label_specific_category {
            get {
                return ResourceManager.GetString("label_specific_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquibase SQL data type.
        /// </summary>
        public static string label_sql_data_type {
            get {
                return ResourceManager.GetString("label_sql_data_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super types.
        /// </summary>
        public static string label_supertypes {
            get {
                return ResourceManager.GetString("label_supertypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Transient.
        /// </summary>
        public static string label_transient_annotation {
            get {
                return ResourceManager.GetString("label_transient_annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string label_type {
            get {
                return ResourceManager.GetString("label_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to CSV Type.
        /// </summary>
        public static string label_type_csv_path {
            get {
                return ResourceManager.GetString("label_type_csv_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type element.
        /// </summary>
        public static string label_type_element {
            get {
                return ResourceManager.GetString("label_type_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to CSV Type Element.
        /// </summary>
        public static string label_type_element_csv_path {
            get {
                return ResourceManager.GetString("label_type_element_csv_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type element data type.
        /// </summary>
        public static string label_type_element_data_type {
            get {
                return ResourceManager.GetString("label_type_element_data_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to super type.
        /// </summary>
        public static string label_type_type_csv_path {
            get {
                return ResourceManager.GetString("label_type_type_csv_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique name.
        /// </summary>
        public static string label_unique_name {
            get {
                return ResourceManager.GetString("label_unique_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase.
        /// </summary>
        public static string label_uppercase {
            get {
                return ResourceManager.GetString("label_uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove &apos;{0}&apos;?.
        /// </summary>
        public static string question_do_you_want_to_remove_object_message {
            get {
                return ResourceManager.GetString("question_do_you_want_to_remove_object_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the selected objects?.
        /// </summary>
        public static string question_do_you_want_to_remove_objects_message {
            get {
                return ResourceManager.GetString("question_do_you_want_to_remove_objects_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ribbon_group_about_label {
            get {
                return ResourceManager.GetString("ribbon_group_about_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string ribbon_group_generate_label {
            get {
                return ResourceManager.GetString("ribbon_group_generate_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ribbon_group_project_label {
            get {
                return ResourceManager.GetString("ribbon_group_project_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ribbon_group_tools_label {
            get {
                return ResourceManager.GetString("ribbon_group_tools_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMON.
        /// </summary>
        public static string ribbon_tab_common_label {
            get {
                return ResourceManager.GetString("ribbon_tab_common_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        public static string ribbon_tab_help_label {
            get {
                return ResourceManager.GetString("ribbon_tab_help_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset &apos;{0}&apos; is used as associated preset for composite preset element &apos;{1}&apos;.
        /// </summary>
        public static string validation_message_preset_is_associated_to_preset_element {
            get {
                return ResourceManager.GetString("validation_message_preset_is_associated_to_preset_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; from folder &apos;{1}&apos; has type element which uses the type as element type from removed folder or subfolder.
        /// </summary>
        public static string validation_message_type_is_used_as_element_type_in_folder {
            get {
                return ResourceManager.GetString("validation_message_type_is_used_as_element_type_in_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is used as a supertype for &apos;{1}&apos;.
        /// </summary>
        public static string validation_message_type_is_used_as_super_type {
            get {
                return ResourceManager.GetString("validation_message_type_is_used_as_super_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; from folder &apos;{1}&apos; uses the type as a supertype from removed folder or subfolder.
        /// </summary>
        public static string validation_message_type_is_used_as_super_type_in_folder {
            get {
                return ResourceManager.GetString("validation_message_type_is_used_as_super_type_in_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is used as a element type for composite type element &apos;{1}&apos;.
        /// </summary>
        public static string validation_message_type_is_used_as_type_element {
            get {
                return ResourceManager.GetString("validation_message_type_is_used_as_type_element", resourceCulture);
            }
        }
    }
}
